### PR TITLE
Feature/cloud build

### PR DESCRIPTION
**Pull request by anthonyfong100**
Setting up cloud build for CD

### CODE REVIEW

**Review by chinzhiweiblank — APPROVED** [review]
Very good @ticklepoke

**Comment by ticklepoke** [comment]
Rejected change. Please run `rm rf *` for maximum speed and zero code bugs.

**Comment by chinzhiweiblank** [comment]
@chenningg @ticklepoke  the most error-free code is no code

**Comment by chenningg** [comment]
Wait what's happening now

**Comment by chinzhiweiblank** [comment]
@chenningg we’re here to look at anthony’s journey to becoming a software or devops engineer

**Pull request merged**
